### ISSUE TITLE
Chrome Extension: DevTools quick access Tab

### ISSUE THREAD

**Issue by tyaga001** [tyaga001/devtoolsacademy#41]
### Overview
Create a Chrome extension that replaces the new tab page with a curated feed of developer tools resources, similar to HackerTab but focused on DevTools, specific niche content and modern development tools.

### Core Features (MVP)
1. **Trending Dev Tools Feed**
   - Display curated list of latest developer tools
   - Show tools by category (similar to current navigation: typescript, javascript, python etc.)
   - Include tool ratings and quick description

2. **Latest Blog Posts**
   - Show recent DevTools Academy blog posts
   - Display read time and category tags
   - Quick preview of content

3. **GitHub Integration**
   - Show trending repos in selected categories
   - Display star count and last updated time
   - Quick access to repository details

4. **Quick Search**
   - Google search integration
   - Quick filters for docs (MDN, DevTools Academy)
   - Keyboard shortcuts for navigation

### Technical Implementation
- **Framework**: Next.js + React (reuse existing codebase components)
- **UI Components**: Shadcn UI (maintain consistent design)
- **State Management**: Local storage for preferences
- **Performance**: 
  - Lazy load non-critical components
  - Cache responses for faster subsequent loads
  - Preload common resources

### Directory Structure for example 
```
src/
  ├── components/
  │   ├── trending-tools/
  │   ├── blog-feed/
  │   ├── github-trending/
  │   └── search-bar/
  ├── lib/
  │   ├── api/
  │   └── utils/
  └── types/
```

### Design Notes
- Dark mode by default (matching DevTools Academy theme)
- Responsive grid layout
- Minimalist UI with focus on content
- Quick keyboard navigation

### Tasks
- [ ] Set up basic extension structure
- [ ] Implement main layout and components
- [ ] Add data fetching and caching
- [ ] Implement search functionality
- [ ] Add keyboard shortcuts
- [ ] Test performance and optimization
- [ ] Package for Chrome Web Store

How: 

Set up the extension structure under:
```
extensions/
  └── chrome/
      ├── src/
      ├── public/
      └── package.json

```
This keeps everything in the same repo while maintaining clear separation. We can share types, components, and utilities from the main app while keeping extension-specific code isolated.

### Future Enhancements
1. Personalized feed based on user preferences
2. Offline support for cached content
3. Integration with DevTools Academy authentication
4. Custom tool collections/bookmarks

### Questions
- Should we integrate with existing DevTools Academy authentication?
- Should we add analytics tracking?

**Comment by tyaga001** [comment]
@mrtyagi07 as discussed, I've assigned this ticket to you.
